spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  datasource:
    postgres:
      url:
      username:
      password:
      driver-class-name:
      hikari:
        pool-name:
        maximum-pool-size:

    oracle:
      url:
      username:
      password:
      driver-class-name:
      hikari:
        pool-name:
        maximum-pool-size:
        read-only: